name: Test VM Execution

on: [push]

jobs:
  test:
    runs-on: self-hosted

    steps:
      - name: Run tests
        shell: powershell
        run: |
          cd C:\sil\gherkin_silfahren_tests
          .\.venv\Scripts\Activate.ps1
          python run_behave.py --stage silver --ini "config\denis.ini" --feature .\features\demo_template.feature --formatter html-pretty

      - name: Prepare report
        if: always()
        shell: powershell
        run: |
          mkdir site -Force
          Copy-Item -Recurse C:\sil\gherkin_silfahren_tests\output\* site\

      - name: Upload artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: report
          path: site

  deploy:
    needs: test
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: report
          path: site

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site

      - name: Deploy Pages
        uses: actions/deploy-pages@v4
